-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgExDHW9vQBlv43jKp
XEzv5efeGleZLoDex2iBSRdfZDigCgYIKoZIzj0DAQehRANCAAQeAtoETWtDGU4t
SAUo+taxUk7sbl07qqL9ExzYyIrn4jd6DXWwd4eHfJ5I9ipkn4QWLw/3Dwzuhmc4
J2wVIiDw
-----END PRIVATE KEY-----